name: 'Create Cross Repo Pull Request'
description: 'Create a pull request in another repository and add labels'

inputs:
  token:
    description: 'GitHub token with permissions to create a PR and add labels'
    required: true
  owner:
    description: 'Owner of the target repository (org or user)'
    required: true
  repo:
    description: 'Name of the target repository'
    required: true
  head:
    description: 'Branch name for the PR (already pushed)'
    required: true
  base:
    description: 'Target base branch'
    required: true
  title:
    description: 'Title of the pull request'
    required: true
  body:
    description: 'Body content of the pull request'
    required: false
    default: ''
  labels:
    description: 'Comma-separated list of labels to add'
    required: false
    default: ''

outputs:
  pr_number:
    description: 'Number of the created PR'
    value: ${{ steps.create-pr.outputs.pr_number }}

runs:
  using: "composite"
  steps:
    - name: Create Pull Request via GitHub API
      id: create-pr
      shell: bash
      run: |
        response=$(curl -s -X POST -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repo }}/pulls \
          -d @- <<EOF
        {
          "title": "${{ inputs.title }}",
          "head": "${{ inputs.head }}",
          "base": "${{ inputs.base }}",
          "body": "${{ inputs.body }}"
        }
        EOF
        )
        echo "Full response: $response"
        pr_number=$(echo "$response" | jq '.number')
        echo "pr_number=$pr_number" >> $GITHUB_OUTPUT

    - name: Add labels to Pull Request (optional)
      if: ${{ inputs.labels != '' }}
      shell: bash
      run: |
        IFS=',' read -ra LABELS <<< "${{ inputs.labels }}"
        labels_json=$(printf '"%s",' "${LABELS[@]}" | sed 's/,$//')
        curl -X POST -H "Authorization: Bearer ${{ inputs.token }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repo }}/issues/${{ steps.create-pr.outputs.pr_number }}/labels \
          -d "{\"labels\": [${labels_json}]}"
